<?php
require_once("header.php");
?>
    <section class="content-section">
        <article class="content-article">
            <div class="content-header">
                <h2>Çerez Politikası</h2>
            </div>
            <hr>
            <div>
                <p style="text-align:justify"><strong>&Ccedil;EREZ (COOKIE) POLİTİKASI</strong></p>
                <p style="text-align:justify">&Ccedil;erez Politikamız, <a href="https://www.keremmert.net/gizlilik-politikasi">Gizlilik Politikamızın</a> bir par&ccedil;asını oluşturur</p>
                <p style="text-align:justify"><strong>&Ccedil;erez (Cookie) Nedir?</strong></p>
                <p style="text-align:justify">G&uuml;n&uuml;m&uuml;zde neredeyse her web sitesi &ccedil;erez kullanmaktadır. Size daha iyi, hızlı ve g&uuml;venli bir deneyim sağlamak i&ccedil;in, &ccedil;oğu internet sitesi gibi biz de &ccedil;erezler kullanıyoruz. &Ccedil;erez, bir web sitesini ziyaret ettiğinizde cihazınıza (&ouml;rneğin; bilgisayar veya cep telefonu) depolanan k&uuml;&ccedil;&uuml;k bir metin dosyasıdır. &Ccedil;erezler, bir web sitesini ilk ziyaretiniz sırasında tarayıcınız aracılığıyla cihazınıza depolanabilirler. Aynı siteyi aynı cihazla tekrar ziyaret ettiğinizde tarayıcınız cihazınızda site adına kayıtlı bir &ccedil;erez olup olmadığını kontrol eder. Eğer kayıt var ise, kaydın i&ccedil;indeki veriyi ziyaret etmekte olduğunuz web sitesine iletir. Bu sayede web sitesi, sizin siteyi daha &ouml;nce ziyaret ettiğinizi anlar ve size iletilecek i&ccedil;eriği de ona g&ouml;re tayin eder.</p>
                <p style="text-align:justify"><strong>&Ccedil;erezler Neden Kullanılır?</strong></p>
                <p style="text-align:justify">Bazı &ccedil;erezler, daha &ouml;nceki ziyaretlerinizde kullandığınız tercihlerin web sitesi tarafından hatırlanmasını sağlayarak, sonraki ziyaretlerinizin &ccedil;ok daha kullanıcı dostu ve kişiselleştirilmiş bir deneyim sunmasını sağlar.</p>
                <p style="text-align:justify">Ayrıca, web sitesinde bulunan &uuml;&ccedil;&uuml;nc&uuml; taraflara ait linkler, bu &uuml;&ccedil;&uuml;nc&uuml; taraflara ait gizlilik politikalarına tabi olmakla birlikte, gizlilik uygulamalarına ait sorumluluk keremmert.net&#39;e ait olmamaktadır ve bu bağlamda ilgili link kapsamındaki site ziyaret edildiğinde siteye ait gizlilik politikasının okunması &ouml;nerilmektedir.</p>
                <p style="text-align:justify"><strong>&Ccedil;erez T&uuml;rleri</strong></p>
                <p style="text-align:justify">Ana kullanım amacı kullanıcılara kolaylık sağlamak olan &ccedil;erezler, temel olarak 4 ana grupta toplanmaktadır:</p>
                <ul>
                    <li style="text-align: justify;"><strong>Oturum &Ccedil;erezleri:</strong>&nbsp;Internet sayfaları arasında bilgi taşınması ve kullanıcı tarafından girilen bilgilerin sistemsel olarak hatırlanması gibi &ccedil;eşitli &ouml;zelliklerden faydalanmaya olanak sağlayan &ccedil;erezlerdir ve internet sitesine ait fonksiyonların d&uuml;zg&uuml;n bir şekilde işleyebilmesi i&ccedil;in gereklidir.</li>
                    <li style="text-align: justify;"><strong>Performans &Ccedil;erezleri:</strong>&nbsp;Sayfaların ziyaret edilme frekansı, olası hata iletileri, kullanıcıların ilgili sayfada harcadıkları toplam zaman ile birlikte siteyi kullanım desenleri konularında bilgi toplayan &ccedil;erezlerdir ve internet sitesinin performansını arttırma amacıyla kullanılmaktadır.</li>
                    <li style="text-align: justify;"><strong>Fonksiyonel &Ccedil;erezler:</strong>&nbsp;Kullanıcıya kolaylık sağlanması amacıyla &ouml;nceden se&ccedil;ili olan se&ccedil;eneklerin hatırlatılmasını sağlayan &ccedil;erezlerdir ve internet sitesi kapsamında kullanıcılara gelişmiş Internet &ouml;zellikleri sağlanmasını hedeflemektedir.</li>
                    <li style="text-align: justify;"><strong>Reklam Ve &Uuml;&ccedil;&uuml;nc&uuml; Taraf &Ccedil;erezleri:</strong>&nbsp;&Uuml;&ccedil;&uuml;nc&uuml; parti tedarik&ccedil;ilere ait &ccedil;erezlerdir ve internet sitesindeki bazı fonksiyonların kullanımına ve reklam takibinin yapılmasına olanak sağlamaktadır.</li>
                </ul>
                <p style="text-align:justify"><strong>&Ccedil;erezlerin Kullanım Ama&ccedil;ları</strong></p>
                <p style="text-align:justify">keremmert.net tarafından kullanılmakta olan &ccedil;erezlere ait kullanım ama&ccedil;ları aşağıdaki gibidir:</p>
                <ul>
                    <li style="text-align: justify;"><strong>G&uuml;venlik ama&ccedil;lı kullanımlar:</strong>&nbsp; keremmert.net, sistemlerinin idaresi ve g&uuml;venliğinin sağlanması amacıyla, bu sitedeki fonksiyonlardan yararlanmayı sağlayan veyahut d&uuml;zensiz davranışları tespit eden &ccedil;erezler kullanabilmektedir.</li>
                    <li style="text-align: justify;"><strong>İşlevselliğe y&ouml;nelik kullanımlar:</strong>&nbsp; keremmert.net, sistemlerinin kullanımını kolaylaştırmak ve kullanıcı &ouml;zelinde kullanım &ouml;zellikleri sağlamak amacıyla, kullanıcıların bilgilerini ve ge&ccedil;miş se&ccedil;imlerini hatırlatan &ccedil;erezler kullanabilmektedir.</li>
                    <li style="text-align: justify;"><strong>Performansa y&ouml;nelik kullanımlar:</strong>&nbsp; keremmert.net, sistemlerinin performansının artırılması ve &ouml;l&ccedil;&uuml;lmesi amacıyla, g&ouml;nderilen iletilerle olan etkileşimi ve kullanıcı davranışlarını değerlendiren ve analiz eden &ccedil;erezler kullanabilmektedir.</li>
                    <li style="text-align: justify;"><strong>Reklam ama&ccedil;lı kullanımlar:</strong>&nbsp; keremmert.net, kendine veya &uuml;&ccedil;&uuml;nc&uuml; taraflara ait sistemlerin &uuml;zerinden kullanıcıların ilgi alanları kapsamında reklam ve benzeri i&ccedil;eriklerin iletilmesi amacıyla, bu reklamların etkinliğini &ouml;l&ccedil;en veya tıklanma durumunu analiz eden &ccedil;erezler kullanabilmektedir.</li>
                </ul>
                <p style="text-align:justify"><strong>Reklam Ama&ccedil;lı &Ccedil;erez Kullanımımız</strong></p>
                <p style="text-align:justify">keremmert.net, Google Adsense reklam sistemi kullanmaktadır. Bu sistem Google tarafından İ&ccedil;erik i&ccedil;in AdSense reklamlarının g&ouml;r&uuml;nt&uuml;lendiği yayıncı web sitelerinde sunulan reklamlarda kullanalan&nbsp;<a href="http://www.doubleclick.com/privacy/faq.aspx" rel="noreferrer noopener" target="_blank">DoubleClick DART</a>&nbsp;&ccedil;erezi i&ccedil;erir.</p>
                <p style="text-align:justify">&Uuml;&ccedil;&uuml;nc&uuml; taraf satıcı olarak Google, sitemizde reklam yayınlamak i&ccedil;in &ccedil;erezlerden yararlanır. Bu &ccedil;erezlerini kullanarak kullanıcılarınıza, sitenize ve İnternet&rsquo;teki diğer sitelere yaptıkları ziyaretlere dayalı reklamlar sunar.&nbsp;<a href="http://www.google.com/privacy_ads.html" rel="noreferrer noopener" target="_blank">Google reklam ve i&ccedil;erik ağı gizlilik politikasını</a>&nbsp;ziyaret ederek DART &ccedil;erezinin kullanılmasını engelleyebilirsiniz.</p>
                <p style="text-align:justify">Google Web sitemizi ziyaret ettiği zamanlarda reklam hizmeti vermek i&ccedil;in &uuml;&ccedil;&uuml;nc&uuml; taraf reklam şirketlerini kullanmaktadır. S&ouml;z konusu şirketler, bu sitelere ve diğer web sitelerine yaptığınız ziyaretlerden elde ettikleri (adınız, adresiniz, e-posta adresiniz veya telefon numaranız dışındaki) bilgileri ilginizi &ccedil;ekecek &uuml;r&uuml;n ve hizmetlerin reklamını size g&ouml;stermek i&ccedil;in kullanabilir. Bu uygulama hakkında bilgi edinmek i&ccedil;in ve s&ouml;z konusu bilgilerin bu şirketler tarafından kullanılmasını engellemek &uuml;zere se&ccedil;eneklerinizin neler olduğunu &ouml;ğrenmek ve daha fazla bilgi i&ccedil;in&nbsp;<a href="http://www.networkadvertising.org/sites/default/files/imce/principles.pdf" rel="noreferrer noopener" target="_blank">NAI Self-Regulatory principles for publishers (PDF)</a>&nbsp;belgesinin A Eki&rsquo;nden yararlanabilirsiniz.</p>
                <p style="text-align:justify"><strong>&Ccedil;erezleri Kontrol Etme ve Silme</strong></p>
                <p style="text-align:justify">&Ccedil;erezlerin kullanımına ilişkin tercihlerinizi değiştirmek ya da &ccedil;erezleri engellemek veya silmek i&ccedil;in tarayıcınızın ayarlarını değiştirmeniz yeterlidir. Bir&ccedil;ok tarayıcı &ccedil;erezleri kontrol edebilmeniz i&ccedil;in size &ccedil;erezleri kabul etme veya reddetme, yalnızca belirli t&uuml;rdeki &ccedil;erezleri kabul etme ya da bir web sitesi cihazınıza &ccedil;erez depolamayı talep ettiğinde tarayıcı tarafından uyarılma se&ccedil;eneği sunar. Aynı zamanda daha &ouml;nce tarayıcınıza kaydedilmiş &ccedil;erezlerin silinmesi de m&uuml;mk&uuml;nd&uuml;r. &Ccedil;erezleri kontrol edilmesine veya silinmesine ilişkin işlemler kullandığınız tarayıcıya g&ouml;re değişebilmektedir. Bazı pop&uuml;ler tarayıcıların &ccedil;erezlere izin verme ya da &ccedil;erezleri engelleme veya silme talimatlarına aşağıdaki linklerden ulaşılması m&uuml;mk&uuml;nd&uuml;r.</p>
                <p style="text-align:justify">&Ccedil;erez kullanım se&ccedil;iminin değiştirilmesine ait y&ouml;ntem, tarayıcı tipine bağlı olarak değişmekte olup, ilgili hizmet sağlayıcıdan dilendiği zaman &ouml;ğrenilebilmektedir.</p>
                <p style="text-align:justify">Bu politikanın en son g&uuml;ncellendiği tarih: 22/02/2023</p>
            </div>
        </article>
    </section>
<?php
require_once("footer.php");